### ISSUE TITLE
Use for production

### ISSUE THREAD

**Issue by omariosouto** [obetomuniz/reeakt#3]
Hi @obetomuniz, thanks for your boilerplate. I want to know if can I use your boilerplate for production with no problems?

**Comment by obetomuniz** [comment]
Hi @omariosouto. Yes, you can. The good part of this boilerplate is the flexibility to remove/replace features easily.

**Comment by omariosouto** [comment]
Thanks! Run the npm start with babel-node, has no problems?

**Comment by obetomuniz** [comment]
reeakt already has a `npm run start` instruction as you can see in the [documentation](https://github.com/obetomuniz/reeakt#build-and-run-the-production-server). You can replace it to use your own configurations but probably will affect the built-in functionalities of the boilerplate.
